create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  first_name text,
  purchase_date timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.content (
  id bigint generated by default as identity primary key,
  day integer not null unique check (day between 1 and 30),
  title text not null,
  body text not null,
  cta text not null
);

alter table public.users enable row level security;
alter table public.content enable row level security;

drop policy if exists "Users can read own access" on public.users;
create policy "Users can read own access"
on public.users
for select
using (email = auth.jwt() ->> 'email');

drop policy if exists "Users can read content" on public.content;
create policy "Users can read content"
on public.content
for select
using (auth.role() = 'authenticated');

insert into public.content (day, title, body, cta) values
(1,
'Como escolher o fotógrafo ideal para o seu casamento sem arrependimentos',
'Escolher o fotógrafo do casamento não é apenas escolher imagens bonitas. É escolher a pessoa que vai guardar a memória de um dos dias mais importantes da sua vida.

Antes de decidir, veja portefólios completos, confirme se o estilo combina convosco e perceba como o profissional conduz os momentos mais delicados do dia.

A melhor escolha é aquela que vos deixa tranquilos antes, durante e depois do casamento.',
'Guarde este post para quando começar a procurar fornecedores.'),
(2,
'3 sinais de que um venue combina com o casamento que os noivos imaginam',
'O espaço certo não é apenas bonito. É funcional, confortável e coerente com a experiência que os noivos querem viver.

Antes de fechar a data, olhem para a luz, a circulação dos convidados, o plano B e a forma como a equipa do espaço comunica.

Quando o venue facilita o dia, tudo parece mais leve.',
'Envie este post aos noivos que estão a visitar espaços esta semana.'),
(3,
'O detalhe que torna uma reunião com fornecedores muito mais tranquila',
'Uma reunião produtiva começa antes da chamada ou da visita. Levar perguntas certas evita dúvidas soltas e decisões feitas à pressa.

Prepare uma pequena lista com prioridades, limites, prazos e expectativas. Isso ajuda o fornecedor a responder com clareza.

Menos improviso. Mais segurança.',
'Guarde este post para preparar a sua próxima reunião.'),
(4,
'Como evitar decisões por impulso durante a organização do casamento',
'A emoção faz parte do processo, mas nem todas as decisões precisam de ser tomadas no momento.

Quando surgir uma escolha importante, voltem ao orçamento, ao estilo do casamento e à experiência que querem proporcionar aos convidados.

Boas decisões continuam a fazer sentido no dia seguinte.',
'Partilhe este post com quem está a organizar o casamento.'),
(5,
'A pergunta que ajuda os noivos a escolher melhor cada fornecedor',
'Antes de comparar preços, os noivos devem perguntar: esta pessoa deixa-nos mais tranquilos?

Um bom fornecedor não entrega apenas um serviço. Entrega confiança, clareza e presença nos momentos em que mais importa.

Isso faz diferença em todo o processo.',
'Guarde este post para rever antes de fechar fornecedores.'),
(6,
'Porque o plano B não deve ser tratado como plano secundário',
'O plano B também faz parte do casamento. Quando é pensado com cuidado, deixa de parecer uma solução de emergência.

Chuva, atrasos ou mudanças de última hora tornam-se mais simples quando todos sabem o que fazer.

Preparação é uma forma de tranquilidade.',
'Envie este post aos noivos que vão casar ao ar livre.'),
(7,
'O que os noivos devem confirmar antes de assinar um contrato',
'Antes de assinar, leiam prazos, condições de cancelamento, horários, valores extra e tudo o que está incluído.

Um contrato claro protege os noivos e também o fornecedor.

As melhores relações profissionais começam com expectativas bem alinhadas.',
'Guarde este post antes de fechar o próximo contrato.'),
(8,
'Como perceber se o estilo visual do casamento está coerente',
'A coerência aparece quando flores, estacionário, espaço, iluminação e decoração contam a mesma história.

Não é preciso repetir tudo. É preciso que tudo converse.

Quando existe uma direção clara, cada detalhe parece intencional.',
'Guarde este post para rever o moodboard do casamento.'),
(9,
'O erro mais comum ao construir a timeline do casamento',
'O erro mais comum é preencher o dia sem margem.

Um casamento precisa de tempo para deslocações, fotografias, imprevistos e pausas reais.

Uma timeline elegante não é apertada. É fluida.',
'Partilhe este post com noivos em fase de planeamento.'),
(10,
'Como escolher fornecedores que trabalham bem em equipa',
'Um casamento acontece melhor quando os fornecedores comunicam entre si.

Experiência, abertura e respeito pelo trabalho dos outros fazem diferença no ritmo do dia.

O resultado aparece nos detalhes e na tranquilidade dos noivos.',
'Guarde este post para a fase de seleção de fornecedores.'),
(11,
'Porque a experiência dos convidados começa antes da cerimónia',
'A experiência começa no convite, nas informações claras, na chegada ao espaço e na forma como tudo flui.

Quando os convidados se sentem orientados, vivem o dia com mais presença.

Hospitalidade também é planeamento.',
'Envie este post aos noivos que querem cuidar bem dos convidados.'),
(12,
'3 erros que os noivos cometem ao escolher o venue',
'Escolher um venue só pela beleza pode trazer surpresas difíceis depois.

Antes de decidir, confirmem capacidade real, plano B, horários, acessos e tudo o que está incluído.

O espaço certo deve ser bonito, mas também deve funcionar bem.',
'Guarde este post para quando começar a visitar venues.'),
(13,
'Como manter o orçamento do casamento sob controlo',
'O orçamento precisa de prioridades claras.

Definam o que é essencial, o que é desejável e o que pode sair sem comprometer a experiência.

Quando cada escolha tem lugar, o processo fica mais leve.',
'Guarde este post para rever antes da próxima decisão.'),
(14,
'O que deve estar alinhado antes da prova de decoração',
'Antes da prova, confirmem paleta, estilo, proporções, flores disponíveis e prioridades do casal.

Quanto mais clara for a direção, mais produtiva será a reunião.

Decisões bonitas nascem de briefings bem feitos.',
'Envie este post aos noivos que estão a fechar decoração.'),
(15,
'Como evitar excesso de referências no casamento',
'Muitas referências podem confundir mais do que ajudar.

Escolham poucas imagens, mas com intenção. Procurem padrões: cores, texturas, ambiente e sensação.

O objetivo não é copiar. É encontrar direção.',
'Guarde este post antes de montar o moodboard.'),
(16,
'Porque a comunicação com os noivos precisa de ritmo',
'Comunicação constante não significa mensagens a toda a hora.

Significa pontos de contacto claros, próximos passos definidos e respostas que trazem segurança.

Ritmo cria confiança.',
'Partilhe este post com quem está a organizar um casamento.'),
(17,
'A diferença entre bonito e bem planeado',
'Um casamento bonito encanta. Um casamento bem planeado deixa todos tranquilos.

O ideal é quando estética e logística trabalham juntas.

É aí que a experiência se torna memorável.',
'Guarde este post para lembrar durante o planeamento.'),
(18,
'Como preparar os noivos para a semana do casamento',
'Na semana do casamento, os noivos não devem estar a resolver tudo.

Listas finais, contactos, horários e responsabilidades precisam de estar fechados antes.

Essa preparação permite que vivam o momento com mais calma.',
'Envie este post aos noivos que estão perto do grande dia.'),
(19,
'O que torna uma cerimónia mais fluida',
'Uma cerimónia fluida depende de entradas bem coordenadas, música alinhada e pessoas preparadas.

Os detalhes invisíveis são os que fazem tudo parecer natural.

Quando ninguém repara na logística, ela funcionou.',
'Guarde este post para rever com a equipa da cerimónia.'),
(20,
'Como escolher uma paleta de cores sem arrependimentos',
'Uma boa paleta combina com o espaço, a estação e a personalidade dos noivos.

Antes de decidir, imaginem as cores em flores, mesa, estacionário e fotografia.

A paleta certa envelhece bem.',
'Guarde este post para a fase de inspiração.'),
(21,
'Porque os fornecedores precisam de informação clara',
'Bons fornecedores trabalham melhor quando recebem contexto.

Horários, contactos, moradas, expectativas e limitações devem estar acessíveis.

Informação clara reduz imprevistos.',
'Partilhe este post antes de enviar o briefing final.'),
(22,
'Como pensar na experiência da mesa dos convidados',
'A mesa é mais do que decoração. É conforto, conversa, circulação e ritmo do jantar.

Alturas, iluminação e espaço entre elementos fazem diferença.

Uma mesa bonita também precisa de ser vivida.',
'Guarde este post para rever a decoração da sala.'),
(23,
'O detalhe que ajuda a fotografia do casamento',
'A fotografia beneficia de tempo, luz e organização.

Reservar momentos certos para retratos, detalhes e família evita pressa e melhora o resultado.

Boas imagens também são planeadas.',
'Envie este post aos noivos que valorizam fotografia.'),
(24,
'Como decidir o que entra no dia do casamento',
'Nem tudo o que é bonito precisa de entrar.

Cada detalhe deve servir a experiência, a história ou a logística do dia.

Editar também é uma forma de elegância.',
'Guarde este post quando sentir excesso de ideias.'),
(25,
'Porque o alinhamento final evita stress',
'Uma reunião final com noivos e fornecedores ajuda a fechar pontas soltas.

Confirmar horários, contactos e responsabilidades reduz dúvidas na semana do casamento.

Clareza antes. Presença no dia.',
'Partilhe este post antes da reunião final.'),
(26,
'Como criar uma entrada dos noivos mais especial',
'A entrada dos noivos ganha força quando música, timing e ambiente estão alinhados.

Não precisa de ser exagerada. Precisa de fazer sentido para eles.

Momentos memoráveis costumam ser simples e bem conduzidos.',
'Guarde este post para pensar na entrada da festa.'),
(27,
'O que considerar no plano de lugares',
'O plano de lugares influencia conversas, conforto e ritmo do jantar.

Pensem em relações, mobilidade, crianças, famílias e dinâmica da sala.

Um bom plano evita desconfortos invisíveis.',
'Envie este post aos noivos que estão a organizar mesas.'),
(28,
'Como fechar detalhes sem perder leveza',
'Na reta final, é fácil querer rever tudo vezes sem conta.

Definam uma data para fechar decisões e confiem no plano construído.

Leveza também vem de saber parar.',
'Guarde este post para a fase final do casamento.'),
(29,
'Porque o dia do casamento precisa de margem',
'Margem é o que permite respirar.

Pequenos atrasos, retoques, deslocações e emoções precisam de espaço na timeline.

Um dia bem planeado não vive no limite.',
'Partilhe este post com quem está a construir a timeline.'),
(30,
'O lembrete final para os noivos antes do casamento',
'Depois de tantas decisões, chega o momento de confiar.

O essencial está preparado. As pessoas certas estão alinhadas. O dia já não precisa de controlo total.

Agora é tempo de viver.',
'Guarde este post para a semana do casamento.')
on conflict (day) do update set
  title = excluded.title,
  body = excluded.body,
  cta = excluded.cta;
