create extension if not exists pgcrypto;

-- ─── Tabela users ─────────────────────────────────────────────
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  first_name text,
  purchase_date timestamptz not null,
  created_at timestamptz not null default now()
);

-- Adicionar coluna products se ainda não existir
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'users'
      and column_name = 'products'
  ) then
    alter table public.users add column products text[] not null default '{}';
    -- Migrar utilizadores existentes para wedding
    update public.users set products = '{wedding}' where array_length(products, 1) is null or array_length(products, 1) = 0;
  end if;
end $$;

-- ─── Tabela content (Wedding) ─────────────────────────────────
create table if not exists public.content (
  id bigint generated by default as identity primary key,
  day integer not null unique check (day between 1 and 30),
  title text not null,
  body text not null,
  cta text not null
);

-- ─── Tabela content_imobiliario ───────────────────────────────
create table if not exists public.content_imobiliario (
  id bigint generated by default as identity primary key,
  day integer not null unique check (day between 1 and 30),
  title text not null,
  body text not null,
  cta text not null
);

-- ─── Row Level Security ───────────────────────────────────────
alter table public.users enable row level security;
alter table public.content enable row level security;
alter table public.content_imobiliario enable row level security;

drop policy if exists "Users can read own access" on public.users;
create policy "Users can read own access"
on public.users for select
using (email = auth.jwt() ->> 'email');

drop policy if exists "Users can read content" on public.content;
create policy "Users can read content"
on public.content for select
using (auth.role() = 'authenticated');

drop policy if exists "Users can read content imobiliario" on public.content_imobiliario;
create policy "Users can read content imobiliario"
on public.content_imobiliario for select
using (auth.role() = 'authenticated');

-- ─── Conteúdo Imobiliário (30 dias) ──────────────────────────
insert into public.content_imobiliario (day, title, body, cta) values
(1,'3 erros que os compradores cometem ao escolher o primeiro imóvel','Comprar o primeiro imóvel é uma das maiores decisões financeiras da vida. A maioria dos compradores foca-se no preço e esquece os encargos reais.\n\nAntes de decidir, confirme localização futura, estado do imóvel, custos de escritura, IMT e condomínio. E perceba qual é a margem de negociação disponível.\n\nA melhor compra é aquela que continua a fazer sentido seis meses depois.','Guarde este post para partilhar com clientes em fase de decisão.'),
(2,'O que ninguém explica sobre a avaliação de um imóvel','A avaliação bancária e o valor de mercado raramente são a mesma coisa.\n\nA avaliação serve o banco. O valor de mercado serve a negociação.\n\nPerceber a diferença pode mudar completamente a estratégia de compra.','Guarde este post para explicar a clientes em fase de financiamento.'),
(3,'Como preparar um imóvel para venda sem gastar demasiado','A primeira impressão define o interesse. E a primeira impressão começa nas fotografias.\n\nLimpeza, organização, luz natural e pequenas reparações fazem mais diferença do que uma remodelação completa.\n\nVender bem começa antes da visita.','Envie este post a proprietários que estão a pensar vender.'),
(4,'A pergunta que os compradores devem fazer antes de visitar um imóvel','Antes de marcar uma visita, os compradores devem perguntar: este imóvel resolve o meu problema principal?\n\nLocalização, tipologia, encargos e estado de conservação devem estar alinhados com as prioridades reais.\n\nVisitas bem preparadas tomam melhores decisões.','Guarde este post para partilhar com clientes em fase de procura.'),
(5,'Porque o mercado imobiliário não funciona como parece','O imóvel certo raramente aparece no momento certo.\n\nO mercado move-se rápido. As melhores oportunidades desaparecem antes de aparecerem nos portais.\n\nEstar preparado antes de encontrar o imóvel faz toda a diferença.','Partilhe este post com quem está a pensar comprar casa.'),
(6,'O erro mais comum ao negociar o preço de um imóvel','A maioria das pessoas negoceia apenas o preço.\n\nMas há outros elementos com valor real: data de escritura, equipamentos incluídos, condições de pagamento e obras necessárias.\n\nUma boa negociação olha para o conjunto, não apenas para o número.','Guarde este post antes de entrar em negociação.'),
(7,'Como escolher um consultor imobiliário em vez de um intermediário','Um bom consultor não entrega apenas imóveis. Entrega clareza, contexto e proteção durante todo o processo.\n\nA diferença aparece quando surgem problemas, dúvidas ou pressão de tempo.\n\nNão está a contratar um catálogo. Está a contratar experiência.','Guarde este post para partilhar com quem está a escolher consultores.'),
(8,'5 sinais de que um imóvel tem problemas escondidos','Uma visita cuidadosa revela mais do que as fotografias mostram.\n\nHumidade, cheiros, rachaduras, instalações antigas e pressão de água são detalhes que importam antes da decisão.\n\nVer bem antes de comprar é sempre mais barato do que descobrir depois.','Guarde este post para a próxima visita a um imóvel.'),
(9,'O que perguntar ao proprietário antes de fazer uma proposta','Antes de avançar com uma proposta, perceba porque é que o imóvel está à venda.\n\nA motivação do vendedor influencia a margem de negociação, o prazo de escritura e as condições possíveis.\n\nBoas perguntas revelam mais do que qualquer avaliação.','Guarde este post para preparar a próxima reunião com proprietário.'),
(10,'Como evitar surpresas depois da escritura','A due diligence protege o comprador.\n\nCertidões, caderneta predial, ficha técnica, dívidas e estado do condomínio devem ser verificados antes da escritura.\n\nO que não é confirmado antes pode tornar-se um problema depois.','Guarde este post para rever antes de qualquer escritura.'),
(11,'O que muda quando existe um consultor dedicado','Quando existe um profissional dedicado, os problemas são resolvidos antes de chegarem ao cliente.\n\nNão está apenas a comprar ou a vender um imóvel. Está a gerir uma decisão com impacto real na sua vida.\n\nIsso merece acompanhamento real.','Partilhe este post com quem está a considerar apoio profissional.'),
(12,'A pergunta que quase ninguém faz antes de investir em imobiliário','Antes de investir, a questão essencial não é o rendimento esperado.\n\nÉ: esta decisão faz sentido com a minha situação actual e os meus objectivos a cinco anos?\n\nInvestir bem começa por investir no contexto certo.','Guarde este post para partilhar com investidores em fase de análise.'),
(13,'Porque escolhi trabalhar em imobiliário','Nunca escolhi esta profissão pelo mercado.\n\nEscolhi-a pelas pessoas que estão a tomar uma das decisões mais importantes das suas vidas.\n\nAcompanhar esse processo com honestidade é o que me motiva todos os dias.','O que mais valoriza num processo de compra ou venda?'),
(14,'O momento que mais me marcou nesta profissão','Os momentos que ficam raramente são os negócios fechados.\n\nSão as histórias por trás de cada decisão. A família que finalmente encontrou o espaço certo. O investidor que percebeu o que realmente queria.\n\nIsso é o que esta profissão tem de único.','Qual foi o momento mais marcante de uma decisão imobiliária que tomou?'),
(15,'O conselho que daria a quem começa no imobiliário','Demorei tempo a perceber que a confiança se constrói antes da venda.\n\nAs pessoas não compram imóveis. Compram tranquilidade, clareza e a certeza de que estão a tomar uma boa decisão.\n\nQuem oferece isso primeiro, fica na memória.','Que conselho daria a alguém que está a entrar no mercado imobiliário?'),
(16,'O lado invisível desta profissão','A maioria das pessoas vê a escritura.\n\nNão vê as semanas de análise, as visitas descartadas, as negociações falhadas e os problemas resolvidos antes de chegarem ao cliente.\n\nQuando tudo parece simples, é porque alguém trabalhou muito para que parecesse.','Já tinha pensado neste lado da profissão?'),
(17,'O que me continua a surpreender no mercado imobiliário','Depois de anos nesta profissão, o mercado continua a surpreender.\n\nCada cliente tem prioridades diferentes. Cada imóvel tem uma história diferente. Cada negociação tem uma dinâmica própria.\n\nÉ por isso que continuo apaixonado pelo que faço.','Qual seria o detalhe mais importante na sua decisão imobiliária?'),
(18,'O que as pessoas não vêem no trabalho de um consultor','Quando tudo corre bem, o trabalho é invisível.\n\nAs visitas descartadas. Os problemas antecipados. As negociações que não chegaram ao cliente.\n\nE sinceramente? Fico satisfeito quando ninguém repara. Porque normalmente significa que funcionou.','Antes de ler este post, imaginava tudo o que acontece antes de uma escritura?'),
(19,'O que muda quando existe planeamento real numa compra imobiliária','A maioria das compras bem-sucedidas começa meses antes da procura activa.\n\nPerceber o orçamento real, os critérios essenciais e o timing certo transforma a experiência de compra.\n\nPreparação não atrasa a decisão. Acelera-a.','Como imagina sentir-se quando encontrar o imóvel certo?'),
(20,'O impacto de uma análise de mercado bem feita','Uma análise de mercado não serve para confirmar o que já sabemos.\n\nServe para perceber o que o mercado está realmente a dizer sobre preço, procura e oportunidade.\n\nDecisões melhores nascem de informação melhor.','Guarde este post para quando começar a analisar o mercado.'),
(21,'O que muda quando existe acompanhamento profissional numa venda','A diferença entre vender sozinho e vender com apoio só se percebe quando surgem complicações.\n\nDocumentação, negociação, visitas, propostas e escritura têm detalhes que fazem diferença no resultado final.\n\nO acompanhamento existe para que o proprietário possa focar-se em decidir, não em gerir.','Qual seria a sua maior preocupação ao vender um imóvel?'),
(22,'Pequenos detalhes que aceleram uma venda','Os compradores formam uma opinião nos primeiros minutos de visita.\n\nLuz, cheiro, organização e temperatura da casa influenciam a percepção de valor.\n\nVender bem é também preparar bem cada visita.','Qual o detalhe que mais recorda de uma casa que visitou?'),
(23,'Antes e depois de uma compra bem acompanhada','Antes: dúvidas constantes, decisões em cima da hora, incerteza sobre o valor real.\n\nDepois: clareza sobre o processo, confiança na decisão, tranquilidade na escritura.\n\nO luxo não é pagar menos. É preocupar-se menos.','Concorda que tranquilidade também tem valor numa compra imobiliária?'),
(24,'O que os clientes mais valorizam depois de fechar negócio','Nunca ouvi um cliente dizer: o melhor foi a burocracia resolvida rapidamente.\n\nO que fica é a sensação de ter tomado a decisão certa, no momento certo, com a informação certa.\n\nEsse é o verdadeiro resultado do acompanhamento profissional.','Qual é a sensação que gostaria de ter depois de fechar um negócio imobiliário?'),
(25,'Quando faz sentido procurar um consultor imobiliário?','A maioria das pessoas procura ajuda quando o processo já está complicado.\n\nMas as decisões mais importantes — definir orçamento, perceber o mercado, escolher critérios — acontecem no início.\n\nQuem tem orientação desde cedo toma melhores decisões ao longo de todo o processo.','Em que fase está actualmente na sua jornada imobiliária?'),
(26,'Quanto custa realmente não ter apoio profissional?','Nem todos os custos aparecem na escritura.\n\nTempo perdido, decisões precipitadas, negociações mal conduzidas e problemas não antecipados têm custos reais.\n\nO apoio profissional não é uma despesa. É protecção.','Já tinha pensado desta forma?'),
(27,'Os sinais de que precisa de apoio na sua decisão imobiliária','Se está constantemente a duvidar da sua decisão, este post é para si.\n\nPrecisa de apoio se: não sabe por onde começar, tem demasiadas opções sem critério, sente que o mercado o ultrapassa ou tem receio de tomar a decisão errada.\n\nPedir orientação não é fraqueza. É inteligência.','Qual destes sinais mais reconhece em si?'),
(28,'O que acontece na primeira reunião com um consultor','A primeira reunião não serve para mostrar imóveis.\n\nServe para perceber o que o cliente realmente precisa, quais são as suas prioridades e qual é o contexto real da decisão.\n\nA confiança constrói-se antes de qualquer proposta.','Qual seria a primeira pergunta que me faria?'),
(29,'As perguntas que os clientes mais me fazem','As perguntas mudam. As preocupações são sempre as mesmas.\n\nPor trás de quase todas as dúvidas existe uma: vou tomar a decisão certa?\n\nEssa é uma preocupação completamente normal. E é exactamente para isso que existe acompanhamento profissional.','Qual é a dúvida que ainda não conseguiu esclarecer?'),
(30,'Está a pensar comprar, vender ou investir? Vamos conversar.','A maioria das pessoas não precisa de mais informação sobre o mercado.\n\nPrecisa de clareza sobre a sua situação específica.\n\nSe está a considerar uma decisão imobiliária e quer perceber qual é o próximo passo certo para si, estou disponível para conversar.','Envie uma mensagem e conte-me em que fase está da sua jornada imobiliária.')
on conflict (day) do update set
  title = excluded.title,
  body = excluded.body,
  cta = excluded.cta;
